name: Cookiecutter smoke test

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'template/**'

jobs:
  cookiecutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cookiecutter
        run: python -m pip install --upgrade pip && pip install cookiecutter

      - name: Run cookiecutter smoke test
        run: |
          # Run cookiecutter pointing at the nested template directory
          cookiecutter template --no-input --output-dir generated
