name: Cookiecutter smoke test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cookiecutter-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install cookiecutter
        run: |
          python -m pip install --upgrade pip
          pip install cookiecutter

      - name: Run cookiecutter (no-input, template dir)
        run: |
          mkdir -p generated
          python3 -m cookiecutter . --no-input --directory=template --output-dir generated

      - name: List generated
        run: |
          echo "Generated files:" && ls -la generated || true
